### PR TITLE
(Done)pr/up&going/ch3/#IntoYDKJS

### PR DESCRIPTION
**Pull request by jlcasasg**
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

### CODE REVIEW

**Comment by EstebanMarin** [comment]
Thanks I added you to the `README.md` file. Many thanks for the contribution, please give us a star in github and share your contribution!

More contribution are welcomed

**Comment by EstebanMarin** [comment]
https://github.com/You-Dont-Know-JS-ES/Traduccion Check in in le lower part of the readme file

**Comment by jlcasasg** [comment]
@EstebanMarin thank you very much! I will contribute more for this nice project :3

**Comment by mballeng91** [comment]
@jlcasasg: Please have in mind to avoid literal translations. 

For example 'Esto no es una buena cosa' could be changed for 'Esto no es tan bueno', and be carefull of spanish sentences. '¿De que se tratan todo este libro?' could be changed for '¿De que se trata esta serie?'. Please fix that and we'll be ready to merge! Thanks again for contributing.

**Comment by jlcasasg** [comment]
@mballeng91 Thank for for your feedback, I update the file :)

**Comment by mballeng91** [comment]
@jlcasasg Thanks a lot!

**Pull request merged**
