### PR TITLE
[InProgress]pr/up&going/ch2/###intojs

### PR DESCRIPTION
**Pull request by Zenfeuer**
PR for Chapter 2: Into JavaScript

### CODE REVIEW

**Comment by mballeng91** [comment]
Thanks @Zenfeuer for your contribution!

**Comment by mballeng91** [comment]
I'm sorry I merged the section by mistake... But We'll have a new pull request for this. Please use https://github.com/You-Dont-Know-JS-ES/Traduccion/pull/27 in order to continue the translation of this section. Thanks for your comprehension!

**Comment by EstebanMarin** [comment]
@mballeng91 @Zenfeuer Can you guys please open a PR. I want to add you in the contributors Readme page.  I added a bot to help me with that. 
Thanks!

**Comment by EstebanMarin** [comment]
Guys I will add you manually! So check the readme file today

**Pull request merged**
