### PR TITLE
[Done]scope&closures/ch1/whatIsScope/#CompilerTheory

### PR DESCRIPTION
**Pull request by SamuelVera**
Hope I can get this to 'done' in 2 or 3 weeks, will depend on how much free time i've got.
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)**.

### CODE REVIEW

**Comment by EstebanMarin** [comment]
Cool. However, if you have limited time, why don't commit to a smaller scope, something that you can deliver in less than that time frame. That way you can manage to contribute faster.

**Comment by SamuelVera** [comment]
Sounds Better that way, i'll translate the intro and Compiler Theory. But how do I exactly put it in the pr name? Like this [InProgress]scope&closures/ch1/whatIsScope/CompilerTheory ?

**Comment by EstebanMarin** [comment]
Yes. Dont worry too much on the naming though, the most important part is: YOUR CONTRIBUTION!!

**Comment by EstebanMarin** [comment]
Hey @SamuelVera many thanks!! this seems soon to be finished!

So you call the shot for us to merge it, I suggest you add a picture to your Github profile. So when we add you, everyone can see your face!

Cheers again!

**Comment by SamuelVera** [comment]
@EstebanMarin Done! And i'll take your advice and add a profile pic later lel

**Comment by EstebanMarin** [comment]
@SamuelVera remember to change the PR from `Draft`, so I can merge it when is ready.

Best and good luck

**Pull request merged**
