### PR TITLE
Revert "[InProgress]pr/up&going/ch2/###intojs"

### PR DESCRIPTION
**Pull request by mballeng91**
Reverts You-Dont-Know-JS-ES/Traduccion#24

### CODE REVIEW

**Comment by Zenfeuer** [comment]
@mballeng91 I have permission issues when I try to update this branch from my fork.

Any additional steps that I need to make?

**Comment by mballeng91** [comment]
I don´t think you need any additional privilegies to update a branch... Please check you get yout local repository updated with git pull and try again. If it doesn´t work... Feel free to create a new branch please. I'm sorry for this inconvenience. @mballeng91

**Comment by Zenfeuer** [comment]
@mballeng91 I keep getting permission issues, because I'm trying to work in the upstream branch (upstream/revert-24-pr/up&going/ch2/###intojs), If I work in my local branch from my fork I got no problems but the changes are not reflected here. So, I keep working on my branch and you after change the from branch for this PR? Any suggestions?

**Comment by mballeng91** [comment]
@Zenfeuer I'm sorry we have fell into this problem. Could you please create a new branch for 'IntoJs' ?section this way we will be ready. :)

**Pull request closed without merging**
