### PR TITLE
[DONE]pr/up&going/ch3/###this&objectprototypes

### PR DESCRIPTION
**Pull request by Zenfeuer**
Initial commit

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

### CODE REVIEW

**Comment by Zenfeuer** [comment]
Hi @mballeng91 , this is ready for review, thanks!

**Comment by EstebanMarin** [comment]
Thanks for your time!

**Comment by EstebanMarin** [comment]
By the way, I noticed that you are very active in the repo, I am more that happy to make you a maintainer so you can commit directly and also onw the repo too, let me know if you are keen?

**Comment by Zenfeuer** [comment]
> By the way, I noticed that you are very active in the repo, I am more that happy to make you a maintainer so you can commit directly and also onw the repo too, let me know if you are keen?

Hi @EstebanMarin , thanks, it would be awesome. Yes, I'm going to keep contribuiting, I have full interest in this project :)

**Pull request merged**
