### PR TITLE
[Done]pr/up&going/ch1/###scope

### PR DESCRIPTION
**Pull request by Zenfeuer**
Moving PR to new repo.

### CODE REVIEW

**Comment by mballeng91** [comment]
Thanks again for your contribution @Zenfeuer . Im glad of seeing you're interested in being a new contributor! Please remember to avoid addressing the reader as familiar. For example instead of using "podrías" use "usted podría" in order to mantain book formality. I'm looking forward to review your branch when it's done. Best regards, @mballeng91

**Comment by Zenfeuer** [comment]
Im going to apply your suggestions, tthanks @mballeng91

**Comment by mballeng91** [comment]
Thanks @Zenfeuer for the contribution, could you please do an interactive rebase of the branch? This way we all can review changes in one single commit. If you're not sure about how to do that please let me know to give you some guidance on that!

**Comment by mballeng91** [comment]
> Hi @mballeng91 , I did the interactive rebase but I think I did something wrong, could you please give some guidance on that? Thanks :)

Of course... be sure you're currently in your branch version of the book, I assume you've already Git installed on your machine and follow these steps on any command line tool: 

1. Type `git rebase -i HEAD~x`  where x is the number of commits you want to rebase.
2. A vim editor will be prompted and you must see a list of all your commits made. Be sure you leave the first one as it is, or maybe you want to change the commit message change the `pick` for a `r` that stands for reword. After that, change the rest of the commits that have a `pick` for an `f` that stands for fix.
3. You'll be directed as you were doing your first commit until the last commit step by step. (That takes around 10 seconds normally)
4. If everything is being doing OK , do `git push -f --set-upstream...<name of the branch>` and all commits will be replaced by the one you picked in step 2 but with all changes of course.

Note: Have a backup of the file in case something fails so we don't loose the tentative new version.
don´t hesitate on contacting us in case of doubts!

Regards!!! @mballeng91

**Comment by Zenfeuer** [comment]
Hi @mballeng91 , the last step it does not work for me, that command throws an error. Also, I think my branch is already messed up by the first erroneous rebase that I did. I was thinking to create a new branch with the changes stacked in one commit and create a new PR with that.

**Comment by mballeng91** [comment]
> Hi @mballeng91 , the last step it does not work for me, that command throws an error. Also, I think my branch is already messed up by the first erroneous rebase that I did. I was thinking to create a new branch with the changes stacked in one commit and create a new PR with that.



> Hi @mballeng91 , the last step it does not work for me, that command throws an error. Also, I think my branch is already messed up by the first erroneous rebase that I did. I was thinking to create a new branch with the changes stacked in one commit and create a new PR with that.

Hi @Zenfeuer thanks for following those steps. Please try again with this command on step 4 `git push -f --set-upstream origin pr/UpAndGoing/ch1/##Scope` maybe i wasn´t clear on that one... I'm looking forward on your answer. Regards!

**Comment by Zenfeuer** [comment]
Hi @mballeng91, thanks for your help. Now the command works but I don't still achieve the desired behavior, so I created a new branch with the changes and a new freash PR. Thanks :)

**Pull request closed without merging**
