### PR TITLE
[Done]pr/up&going/ch1/review

### PR DESCRIPTION
**Pull request by Zenfeuer**
This PR is intended to make corrections and suggestions to the Chapter 1 that is almost finished.

### CODE REVIEW

**Comment by Zenfeuer** [comment]
Hi @EstebanMarin , yes, I want to contribute more. Could I begin with the next chapter?

**Comment by mballeng91** [comment]
> Hi @EstebanMarin , yes, I want to contribute more. Could I begin with the next chapter?
@Zenfeuer : Sure, please go ahead on the traduction the way you want

**Comment by Zenfeuer** [comment]
Ok, Im on it then. Thanks!

**Comment by Zenfeuer** [comment]
Btw, could you put me as collaborator? I would appreciate that :)

@EstebanMarin @mballeng91

**Pull request merged**
